"""Stateful protocol simulation layer for the HIL-RIG transport packet model.

This module deliberately works above the byte/word layer.  Devices exchange
``TransportPacket`` objects directly, which keeps this file focused on protocol
behaviour rather than encoding, framing, or physical transport details.

The classes are designed for assessment and experimentation.  A caller can pass
packets between ``HostDevice`` and ``RigDevice`` normally, or deliberately not
pass them, delay them, or mutate them to simulate dropped packets, corruption,
disconnection, and timeout handling.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

from transport_structure import (
    TransportPacket,
    TransportPacketState,
    TransportStateChangeFlag,
)


NO_STATE_CHANGE = TransportStateChangeFlag.IDLE
HOST_SOURCE_BIT = 0
RIG_SOURCE_BIT = 1


@dataclass
class ProtocolConfig:
    """Timing and retry configuration for protocol simulations.

    All timing values are expressed in milliseconds because the protocol layer is
    intended to be driven by explicit timestamps supplied by tests or simulation
    code.
    """

    keep_alive_interval_ms: int = 500
    keep_alive_timeout_ms: int = 1500
    state_ack_timeout_ms: int = 500
    packet_ack_timeout_ms: int = 500
    armed_timeout_ms: int = 5000
    max_retries: int = 3
    default_host_window_size: int = 1024
    default_rig_window_size: int = 256
    running_window_size: int = 1
    fault_window_size: int = 16
    enter_fault_on_keep_alive_timeout: bool = True


@dataclass
class ProtocolEvent:
    """A timestamped event generated by a protocol device."""

    timestamp_ms: int
    device_name: str
    event_type: str
    message: str
    state_before: TransportPacketState
    state_after: TransportPacketState
    packet: Optional[TransportPacket] = None


@dataclass
class ProtocolStats:
    """Counters useful when comparing protocol behaviour in simulations."""

    packets_sent: int = 0
    packets_received: int = 0
    packets_rejected: int = 0
    packets_dropped_detected: int = 0
    packets_corrupted_detected: int = 0
    keep_alive_packets_sent: int = 0
    keep_alive_packets_received: int = 0
    keep_alive_timeouts: int = 0
    state_changes_requested: int = 0
    state_changes_acknowledged: int = 0
    retransmissions: int = 0
    faults_entered: int = 0


@dataclass
class PacketDeliveryResult:
    """Result returned after a device processes an incoming packet."""

    accepted: bool
    reason: str
    response_packets: list[TransportPacket] = field(default_factory=list)
    events: list[ProtocolEvent] = field(default_factory=list)


class ProtocolFault(RuntimeError):
    """Raised by callers if they want to convert fault events into exceptions."""


class ProtocolDevice:
    """Base class shared by HostDevice and RigDevice.

    The base class owns generic protocol bookkeeping: sequence numbers,
    acknowledgement numbers, keep-alive tracking, state-change acknowledgement
    tracking, event logging, and packet creation.  Child classes implement the
    role-specific state-machine behaviour.
    """

    def __init__(
        self,
        *,
        name: str,
        source_bit: int,
        initial_state: TransportPacketState,
        config: Optional[ProtocolConfig] = None,
    ) -> None:
        self.name = name
        self.source_bit = source_bit
        self.peer_source_bit = 1 - source_bit
        self.state = TransportPacketState(initial_state)
        self.config = config if config is not None else ProtocolConfig()

        self.connected = False
        self.faulted = self.state == TransportPacketState.FAULT

        self.next_sequence_number = 0
        self.expected_peer_sequence_number = 0
        self.last_acknowledgement_number = 0

        self.last_packet_sent_timestamp_ms: Optional[int] = None
        self.last_packet_received_timestamp_ms: Optional[int] = None
        self.last_keep_alive_sent_timestamp_ms: Optional[int] = None
        self.last_keep_alive_received_timestamp_ms: Optional[int] = None

        self.pending_state_change: Optional[TransportPacketState] = None
        self.pending_state_change_since_ms: Optional[int] = None
        self.pending_state_change_retries = 0
        self._pending_state_change_packet: Optional[TransportPacket] = None

        self.event_log: list[ProtocolEvent] = []
        self.stats = ProtocolStats()

    def receive_packet(
        self,
        packet: TransportPacket,
        timestamp_ms: int,
    ) -> PacketDeliveryResult:
        """Process one packet received from the peer.

        The caller controls whether this function is called at all.  Not calling
        it is how tests and simulations model a dropped packet or disconnection.
        """

        accepted, reason = self.validate_received_packet(packet, timestamp_ms)
        if not accepted:
            self.stats.packets_rejected += 1
            event = self.log_event(
                timestamp_ms,
                "packet_rejected",
                reason,
                packet=packet,
            )
            return PacketDeliveryResult(False, reason, events=[event])

        self.connected = True
        self.stats.packets_received += 1
        self.last_packet_received_timestamp_ms = timestamp_ms
        self.expected_peer_sequence_number = max(
            self.expected_peer_sequence_number,
            packet.header.sequence_number + 1,
        )
        self.last_acknowledgement_number = packet.header.acknowledgement_number

        if packet.header.keep_alive_bit:
            self.last_keep_alive_received_timestamp_ms = timestamp_ms
            self.stats.keep_alive_packets_received += 1
            self.log_event(
                timestamp_ms,
                "keep_alive_received",
                "Received keep-alive packet",
                packet=packet,
            )

        if packet.header.state_change_ack:
            self.process_state_change_ack(packet, timestamp_ms)

        response_packets = self.handle_packet_by_state(packet, timestamp_ms)
        return PacketDeliveryResult(
            accepted=True,
            reason="accepted",
            response_packets=response_packets,
            events=list(self.event_log),
        )

    def tick(self, timestamp_ms: int) -> list[TransportPacket]:
        """Advance the device's protocol timers.

        This lets tests model time passing without exchanging a packet.  The
        method may emit keep-alive packets, retransmit pending state-change
        packets, or enter fault state after a timeout.
        """

        outgoing: list[TransportPacket] = []

        if self.faulted:
            return outgoing

        if self.connected and self._keep_alive_timed_out(timestamp_ms):
            self.stats.keep_alive_timeouts += 1
            if self.config.enter_fault_on_keep_alive_timeout:
                outgoing.extend(
                    self.enter_fault("keep-alive timeout", timestamp_ms)
                )
                return outgoing

        if self._state_ack_timed_out(timestamp_ms):
            if self.pending_state_change_retries < self.config.max_retries:
                retransmission = self._retransmit_pending_state_change(timestamp_ms)
                if retransmission is not None:
                    outgoing.append(retransmission)
            else:
                outgoing.extend(
                    self.enter_fault("state-change acknowledgement timeout", timestamp_ms)
                )
                return outgoing

        if self._should_send_keep_alive(timestamp_ms):
            outgoing.append(self.send_keep_alive(timestamp_ms))

        return outgoing

    def build_packet(
        self,
        *,
        timestamp_ms: int,
        payload_bits_as_int: int = 0,
        payload_bit_length: int = 0,
        ack_bit: int = 0,
        rst_bit: int = 0,
        syn_bit: int = 0,
        fin_bit: int = 0,
        current_state: Optional[TransportPacketState] = None,
        change_state_flag: TransportStateChangeFlag | TransportPacketState | int = NO_STATE_CHANGE,
        state_change_ack: int = 0,
        keep_alive_bit: int = 0,
        window_size: Optional[int] = None,
        checksum: int = 0,
    ) -> TransportPacket:
        """Build a ``TransportPacket`` using this device's protocol context."""

        selected_state = self.state if current_state is None else TransportPacketState(current_state)
        selected_window = self.get_window_size() if window_size is None else window_size

        packet = TransportPacket.build(
            sequence_number=self.next_sequence_number,
            acknowledgement_number=self.expected_peer_sequence_number,
            payload_bits_as_int=payload_bits_as_int,
            payload_bit_length=payload_bit_length,
            source_bit=self.source_bit,
            ack_bit=ack_bit,
            rst_bit=rst_bit,
            syn_bit=syn_bit,
            fin_bit=fin_bit,
            current_state=selected_state,
            change_state_flag=TransportStateChangeFlag(int(change_state_flag)),
            state_change_ack=state_change_ack,
            keep_alive_bit=keep_alive_bit,
            reserved=0,
            window_size=selected_window,
            checksum=checksum,
        )

        self.next_sequence_number += 1
        self.stats.packets_sent += 1
        self.last_packet_sent_timestamp_ms = timestamp_ms
        return packet

    def send_keep_alive(self, timestamp_ms: int) -> TransportPacket:
        """Build a keep-alive packet for the current state."""

        packet = self.build_packet(
            timestamp_ms=timestamp_ms,
            ack_bit=1,
            keep_alive_bit=1,
        )
        self.last_keep_alive_sent_timestamp_ms = timestamp_ms
        self.stats.keep_alive_packets_sent += 1
        self.log_event(
            timestamp_ms,
            "keep_alive_sent",
            "Sent keep-alive packet",
            packet=packet,
        )
        return packet

    def request_state_change(
        self,
        new_state: TransportPacketState,
        timestamp_ms: int,
    ) -> TransportPacket:
        """Change local state and notify/request the peer about the new state."""

        state_before = self.state
        self.state = TransportPacketState(new_state)
        self.faulted = self.state == TransportPacketState.FAULT
        self.pending_state_change = self.state
        self.pending_state_change_since_ms = timestamp_ms
        self.pending_state_change_retries = 0
        self.stats.state_changes_requested += 1

        packet = self.build_packet(
            timestamp_ms=timestamp_ms,
            ack_bit=1,
            current_state=self.state,
            change_state_flag=TransportStateChangeFlag(int(self.state)),
            state_change_ack=0,
        )
        self._pending_state_change_packet = packet

        self.log_event(
            timestamp_ms,
            "state_change_requested",
            f"State changed/requested: {state_before.name} -> {self.state.name}",
            state_before=state_before,
            packet=packet,
        )
        return packet

    def acknowledge_state_change(
        self,
        state: TransportPacketState,
        timestamp_ms: int,
    ) -> TransportPacket:
        """Build a state-change acknowledgement packet."""

        packet = self.build_packet(
            timestamp_ms=timestamp_ms,
            ack_bit=1,
            current_state=TransportPacketState(state),
            change_state_flag=TransportStateChangeFlag(int(state)),
            state_change_ack=1,
        )
        self.stats.state_changes_acknowledged += 1
        self.log_event(
            timestamp_ms,
            "state_change_ack_sent",
            f"Acknowledged state change to {TransportPacketState(state).name}",
            packet=packet,
        )
        return packet

    def process_state_change_ack(
        self,
        packet: TransportPacket,
        timestamp_ms: int,
    ) -> None:
        """Clear pending state-change tracking if an acknowledgement matches."""

        acknowledged_state = TransportPacketState(packet.header.current_state)
        if self.pending_state_change is None:
            self.log_event(
                timestamp_ms,
                "unexpected_state_change_ack",
                f"Received state-change acknowledgement for {acknowledged_state.name} with no pending state change",
                packet=packet,
            )
            return

        if acknowledged_state != self.pending_state_change:
            self.log_event(
                timestamp_ms,
                "state_change_ack_mismatch",
                f"Expected acknowledgement for {self.pending_state_change.name}, got {acknowledged_state.name}",
                packet=packet,
            )
            return

        self.pending_state_change = None
        self.pending_state_change_since_ms = None
        self.pending_state_change_retries = 0
        self._pending_state_change_packet = None
        self.stats.state_changes_acknowledged += 1
        self.log_event(
            timestamp_ms,
            "state_change_ack_received",
            f"Received acknowledgement for {acknowledged_state.name}",
            packet=packet,
        )

    def enter_fault(self, reason: str, timestamp_ms: int) -> list[TransportPacket]:
        """Move the device to FAULT and emit a fault notification packet."""

        if self.state == TransportPacketState.FAULT:
            return []

        state_before = self.state
        self.state = TransportPacketState.FAULT
        self.faulted = True
        self.stats.faults_entered += 1
        self.log_event(
            timestamp_ms,
            "fault_entered",
            reason,
            state_before=state_before,
        )
        return [self.request_state_change(TransportPacketState.FAULT, timestamp_ms)]

    def validate_received_packet(
        self,
        packet: TransportPacket,
        timestamp_ms: int,
    ) -> tuple[bool, str]:
        """Validate protocol-level packet properties.

        This is intentionally lightweight.  Higher-level simulation code may
        model corruption by mutating packet fields before delivery, which should
        then be caught here where possible.
        """

        if packet.header.source_bit != self.peer_source_bit:
            self.stats.packets_corrupted_detected += 1
            return False, "unexpected source bit"

        if packet.header.sequence_number < self.expected_peer_sequence_number:
            self.stats.packets_dropped_detected += 1
            return False, "duplicate or stale sequence number"

        if packet.header.acknowledgement_number > self.next_sequence_number:
            self.stats.packets_corrupted_detected += 1
            return False, "acknowledgement number is ahead of sent packets"

        if timestamp_ms < 0:
            return False, "timestamp_ms must be non-negative"

        return True, "accepted"

    def get_window_size(self) -> int:
        """Return the advertised receive window for this device/state."""

        if self.state == TransportPacketState.RUNNING:
            return self.config.running_window_size
        if self.state == TransportPacketState.FAULT:
            return self.config.fault_window_size
        if self.source_bit == HOST_SOURCE_BIT:
            return self.config.default_host_window_size
        return self.config.default_rig_window_size

    def handle_packet_by_state(
        self,
        packet: TransportPacket,
        timestamp_ms: int,
    ) -> list[TransportPacket]:
        """Role-specific packet handling implemented by child classes."""

        raise NotImplementedError

    def log_event(
        self,
        timestamp_ms: int,
        event_type: str,
        message: str,
        *,
        packet: Optional[TransportPacket] = None,
        state_before: Optional[TransportPacketState] = None,
    ) -> ProtocolEvent:
        """Record and return a protocol event."""

        before = self.state if state_before is None else TransportPacketState(state_before)
        event = ProtocolEvent(
            timestamp_ms=timestamp_ms,
            device_name=self.name,
            event_type=event_type,
            message=message,
            state_before=before,
            state_after=self.state,
            packet=packet,
        )
        self.event_log.append(event)
        return event

    def _packet_requests_state_change(self, packet: TransportPacket) -> bool:
        """Return true if the packet carries a non-idle state-change request.

        The current packet header has a 3-bit state-change field but no separate
        valid bit.  For this simulation layer, IDLE is treated as the neutral
        value for ordinary packets.  Explicit reset/return-to-idle behaviours are
        modelled with dedicated methods such as ``reset`` and reporting ACK
        handling.
        """

        return (
            packet.header.state_change_ack == 0
            and TransportStateChangeFlag(packet.header.change_state_flag) != NO_STATE_CHANGE
        )

    def _should_send_keep_alive(self, timestamp_ms: int) -> bool:
        if self.config.keep_alive_interval_ms <= 0:
            return False
        if self.last_keep_alive_sent_timestamp_ms is None:
            if self.connected:
                return True
            return False
        return (
            timestamp_ms - self.last_keep_alive_sent_timestamp_ms
            >= self.config.keep_alive_interval_ms
        )

    def _keep_alive_timed_out(self, timestamp_ms: int) -> bool:
        reference = self.last_packet_received_timestamp_ms
        if self.last_keep_alive_received_timestamp_ms is not None:
            reference = self.last_keep_alive_received_timestamp_ms
        if reference is None:
            return False
        return timestamp_ms - reference >= self.config.keep_alive_timeout_ms

    def _state_ack_timed_out(self, timestamp_ms: int) -> bool:
        if self.pending_state_change is None:
            return False
        if self.pending_state_change_since_ms is None:
            return False
        return timestamp_ms - self.pending_state_change_since_ms >= self.config.state_ack_timeout_ms

    def _retransmit_pending_state_change(self, timestamp_ms: int) -> Optional[TransportPacket]:
        if self.pending_state_change is None:
            return None
        self.pending_state_change_retries += 1
        self.pending_state_change_since_ms = timestamp_ms
        self.stats.retransmissions += 1
        packet = self.build_packet(
            timestamp_ms=timestamp_ms,
            ack_bit=1,
            current_state=self.pending_state_change,
            change_state_flag=TransportStateChangeFlag(int(self.pending_state_change)),
            state_change_ack=0,
        )
        self._pending_state_change_packet = packet
        self.log_event(
            timestamp_ms,
            "state_change_retransmitted",
            f"Retransmitted state change for {self.pending_state_change.name}",
            packet=packet,
        )
        return packet


class HostDevice(ProtocolDevice):
    """Protocol role representing the external host."""

    def __init__(self, config: Optional[ProtocolConfig] = None) -> None:
        super().__init__(
            name="host",
            source_bit=HOST_SOURCE_BIT,
            initial_state=TransportPacketState.IDLE,
            config=config,
        )
        self.rig_state_view = TransportPacketState.IDLE
        self.configuration_packets_sent = 0
        self.result_packets_received = 0
        self.received_result_payloads: list[tuple[int, int]] = []
        self.awaiting_results = False
        self.connection_established = False

    def start_configuration(self, timestamp_ms: int) -> TransportPacket:
        """Request that the rig enter CONFIGURING state."""

        self.connection_established = True
        return self.request_state_change(TransportPacketState.CONFIGURING, timestamp_ms)

    def send_configuration_packet(
        self,
        config_payload: int,
        config_payload_bit_length: int,
        timestamp_ms: int,
    ) -> TransportPacket:
        """Send one logical configuration payload packet to the rig."""

        self.configuration_packets_sent += 1
        return self.build_packet(
            timestamp_ms=timestamp_ms,
            payload_bits_as_int=config_payload,
            payload_bit_length=config_payload_bit_length,
            ack_bit=1,
            current_state=self.rig_state_view,
            change_state_flag=NO_STATE_CHANGE,
        )

    def finish_configuration(self, timestamp_ms: int) -> TransportPacket:
        """Signal that host-side configuration transfer is complete."""

        return self.build_packet(
            timestamp_ms=timestamp_ms,
            payload_bits_as_int=0,
            payload_bit_length=0,
            ack_bit=1,
            fin_bit=1,
            current_state=self.rig_state_view,
            change_state_flag=NO_STATE_CHANGE,
        )

    def send_execute_signal(self, timestamp_ms: int) -> TransportPacket:
        """Request that the rig move from ARMED to RUNNING."""

        return self.request_state_change(TransportPacketState.RUNNING, timestamp_ms)

    def receive_result_packet(self, packet: TransportPacket, timestamp_ms: int) -> None:
        """Record one result/reporting packet from the rig."""

        self.result_packets_received += 1
        self.received_result_payloads.append(
            (packet.payload_bits_as_int, packet.payload_bit_length)
        )
        self.log_event(
            timestamp_ms,
            "result_packet_received",
            "Received result packet from rig",
            packet=packet,
        )

    def confirm_result_transfer_complete(self, timestamp_ms: int) -> TransportPacket:
        """Send an OK-style acknowledgement after result transfer."""

        self.awaiting_results = False
        return self.build_packet(
            timestamp_ms=timestamp_ms,
            ack_bit=1,
            fin_bit=1,
            current_state=self.rig_state_view,
            change_state_flag=NO_STATE_CHANGE,
        )

    def handle_packet_by_state(
        self,
        packet: TransportPacket,
        timestamp_ms: int,
    ) -> list[TransportPacket]:
        """Handle packets received by the host."""

        responses: list[TransportPacket] = []
        reported_state = TransportPacketState(packet.header.current_state)
        self.rig_state_view = reported_state

        if reported_state == TransportPacketState.FAULT:
            self.log_event(
                timestamp_ms,
                "rig_fault_reported",
                "Rig reported FAULT state",
                packet=packet,
            )

        if self._packet_requests_state_change(packet):
            responses.append(self.acknowledge_state_change(reported_state, timestamp_ms))

        if reported_state == TransportPacketState.REPORTING and packet.payload_bit_length > 0:
            self.awaiting_results = True
            self.receive_result_packet(packet, timestamp_ms)

        if reported_state == TransportPacketState.IDLE and self.rig_state_view != TransportPacketState.IDLE:
            self.awaiting_results = False

        return responses


class RigDevice(ProtocolDevice):
    """Protocol role representing the HIL-RIG device."""

    def __init__(self, config: Optional[ProtocolConfig] = None) -> None:
        super().__init__(
            name="rig",
            source_bit=RIG_SOURCE_BIT,
            initial_state=TransportPacketState.IDLE,
            config=config,
        )
        self.configuration_packets_received = 0
        self.configuration_valid = False
        self.execute_required = True
        self.test_started_timestamp_ms: Optional[int] = None
        self.test_completed = False
        self.result_payloads_to_send: list[tuple[int, int]] = []
        self.result_packets_sent = 0

    def handle_packet_by_state(
        self,
        packet: TransportPacket,
        timestamp_ms: int,
    ) -> list[TransportPacket]:
        """Handle packets received by the rig according to its current state."""

        responses: list[TransportPacket] = []

        if packet.header.rst_bit:
            responses.append(self.reset(timestamp_ms))
            return responses

        if self.state == TransportPacketState.IDLE:
            if self._packet_requests_state_change(packet):
                requested_state = TransportPacketState(packet.header.change_state_flag)
                if requested_state == TransportPacketState.CONFIGURING:
                    responses.append(
                        self.request_state_change(TransportPacketState.CONFIGURING, timestamp_ms)
                    )
                    responses.append(
                        self.acknowledge_state_change(TransportPacketState.CONFIGURING, timestamp_ms)
                    )
                elif requested_state == TransportPacketState.RUNNING:
                    responses.extend(
                        self.enter_fault("cannot enter RUNNING directly from IDLE", timestamp_ms)
                    )
            return responses

        if self.state == TransportPacketState.CONFIGURING:
            if packet.payload_bit_length > 0:
                accepted = self.accept_configuration_packet(packet, timestamp_ms)
                if not accepted:
                    responses.extend(
                        self.enter_fault("configuration packet rejected", timestamp_ms)
                    )
                    return responses

            if packet.header.fin_bit:
                responses.append(self.complete_configuration(timestamp_ms))
            return responses

        if self.state == TransportPacketState.ARMED:
            if self._packet_requests_state_change(packet):
                requested_state = TransportPacketState(packet.header.change_state_flag)
                if requested_state == TransportPacketState.RUNNING:
                    responses.append(self.receive_execute_signal(packet, timestamp_ms))
            return responses

        if self.state == TransportPacketState.RUNNING:
            # During RUNNING, normal payload-heavy traffic is deliberately ignored
            # by this high-level model.  Keep-alives are handled by the base class.
            if packet.payload_bit_length > 0:
                self.log_event(
                    timestamp_ms,
                    "running_payload_ignored",
                    "Ignored payload while running",
                    packet=packet,
                )
            return responses

        if self.state == TransportPacketState.REPORTING:
            maybe_transition = self.handle_reporting_ack(packet, timestamp_ms)
            if maybe_transition is not None:
                responses.append(maybe_transition)
            return responses

        if self.state == TransportPacketState.FAULT:
            if packet.header.rst_bit:
                responses.append(self.reset(timestamp_ms))
            return responses

        return responses

    def accept_configuration_packet(
        self,
        packet: TransportPacket,
        timestamp_ms: int,
    ) -> bool:
        """Accept one simulated configuration packet."""

        if self.state != TransportPacketState.CONFIGURING:
            return False
        self.configuration_packets_received += 1
        self.configuration_valid = True
        self.log_event(
            timestamp_ms,
            "configuration_packet_received",
            "Accepted configuration packet",
            packet=packet,
        )
        return True

    def complete_configuration(self, timestamp_ms: int) -> TransportPacket:
        """Simulate configuration completion and move to ARMED or RUNNING."""

        if not self.configuration_valid:
            return self.request_state_change(TransportPacketState.IDLE, timestamp_ms)

        next_state = (
            TransportPacketState.ARMED
            if self.execute_required
            else TransportPacketState.RUNNING
        )
        return self.request_state_change(next_state, timestamp_ms)

    def receive_execute_signal(
        self,
        packet: TransportPacket,
        timestamp_ms: int,
    ) -> TransportPacket:
        """Accept an execute signal and move to RUNNING."""

        self.test_started_timestamp_ms = timestamp_ms
        self.log_event(
            timestamp_ms,
            "execute_signal_received",
            "Received execute signal from host",
            packet=packet,
        )
        return self.request_state_change(TransportPacketState.RUNNING, timestamp_ms)

    def complete_test(self, timestamp_ms: int) -> TransportPacket:
        """Simulate test completion and move to REPORTING."""

        self.test_completed = True
        if not self.result_payloads_to_send:
            self.result_payloads_to_send.append((0, 0))
        return self.request_state_change(TransportPacketState.REPORTING, timestamp_ms)

    def queue_result_payload(
        self,
        payload_bits_as_int: int,
        payload_bit_length: int,
    ) -> None:
        """Queue one logical result payload for later reporting."""

        self.result_payloads_to_send.append((payload_bits_as_int, payload_bit_length))

    def send_result_packet(self, timestamp_ms: int) -> Optional[TransportPacket]:
        """Send one queued result packet while in REPORTING state."""

        if self.state != TransportPacketState.REPORTING:
            return None
        if not self.result_payloads_to_send:
            return None

        payload_bits_as_int, payload_bit_length = self.result_payloads_to_send.pop(0)
        self.result_packets_sent += 1
        packet = self.build_packet(
            timestamp_ms=timestamp_ms,
            payload_bits_as_int=payload_bits_as_int,
            payload_bit_length=payload_bit_length,
            ack_bit=1,
            current_state=TransportPacketState.REPORTING,
            change_state_flag=NO_STATE_CHANGE,
        )
        self.log_event(
            timestamp_ms,
            "result_packet_sent",
            "Sent result packet to host",
            packet=packet,
        )
        return packet

    def handle_reporting_ack(
        self,
        packet: TransportPacket,
        timestamp_ms: int,
    ) -> Optional[TransportPacket]:
        """Handle host acknowledgement that reporting is complete."""

        if packet.header.ack_bit and packet.header.fin_bit:
            self.log_event(
                timestamp_ms,
                "reporting_complete_ack_received",
                "Host acknowledged reporting completion",
                packet=packet,
            )
            return self.request_state_change(TransportPacketState.IDLE, timestamp_ms)
        return None

    def reset(self, timestamp_ms: int) -> TransportPacket:
        """Reset protocol state and notify the peer that the rig is IDLE."""

        state_before = self.state
        self.state = TransportPacketState.IDLE
        self.faulted = False
        self.connected = False
        self.pending_state_change = None
        self.pending_state_change_since_ms = None
        self.pending_state_change_retries = 0
        self._pending_state_change_packet = None
        self.configuration_packets_received = 0
        self.configuration_valid = False
        self.test_started_timestamp_ms = None
        self.test_completed = False
        self.result_payloads_to_send.clear()
        self.result_packets_sent = 0
        packet = self.build_packet(
            timestamp_ms=timestamp_ms,
            ack_bit=1,
            rst_bit=1,
            current_state=TransportPacketState.IDLE,
            change_state_flag=NO_STATE_CHANGE,
        )
        self.log_event(
            timestamp_ms,
            "reset",
            "Rig reset to IDLE",
            packet=packet,
            state_before=state_before,
        )
        return packet
